### ISSUE TITLE
Automating calendar creation

### ISSUE THREAD

**Issue by samuelhaeussler** [klimeryk/recalendar.js#101]
Is there a way to create a calendar with a script and parameters?

**Comment by klimeryk** [comment]
That was basically the previous version of this project: https://github.com/klimeryk/recalendar. That one was in PHP and run only as a script. It's pretty customizeable, but also different libraries were used to generate the PDF, etc. so you won't get the same results.
Curious, what's your use case?

**Comment by samuelhaeussler** [comment]
I know, but I miss the ics import function there :)

I have multiple web calendars which change frequently, so it would be cool to automate the calendar creation process. Maybe with a curl request.

**Comment by klimeryk** [comment]
Ah, I see. It so happens that a community member added ICS support yesterday :) https://github.com/klimeryk/recalendar.js/pull/92. However, as I've noted in https://github.com/klimeryk/recalendar.js/issues/23#issuecomment-1782018231, your use case for importing ICS calendars will not work well with how ReMarkable tablet works. Like I mentioned there, you could probably hack it together (ReMarkable stores PDF annotations in a separate file, you could merge them to the new one, etc.). But if your calendar PDF shifts by one page, it will all be broken. It will be a fragile process and it's not something I'm planning to support in this project 🙇‍♂️
