### ISSUE TITLE
Erstellung 2024

### ISSUE THREAD

**Issue by Kongtendo981** [klimeryk/recalendar.js#108]
Die Erstellung der Monatansicht klapt noch aber bei der Erstellung des Jshreskalenders bricht es immer ab .... warum?

**Comment by klimeryk** [comment]
Sorry, I can only offer support in English.
I also need more information - what are the steps to reproduce? What crashes? The browser, the tab, etc.? Have you tried a different browser/device?

Happy to help, just need more info. Closing for now, please feel free to re-open with the information above 🙇
