### ISSUE TITLE
Feature request : integration of an online calendar.

### ISSUE THREAD

**Issue by espoirMur** [klimeryk/recalendar.js#11]
Allow the integration of a custom google calendar to view the job and planned meetings in advance

**Comment by klimeryk** [comment]
Hi, @espoirMur! This could be a nice feature, but I'm also worried if users would understand the limitations. Especially that the online calendar would be pulled in only once - no further updates to it would propagate to the ReCalendar. It's rather unlikely that your work calendar does _not_ change throughout the year. I'd be worried that the deeper into the year, the more frustrating and counter-productive this would become. But maybe I misunderstood your request - or made false assumptions about people's schedules 😅 

It could be useful, though, if you have a calendar with birthdays, celebrations, etc. 🤔

**Comment by espoirMur** [comment]
Yeah... That makes sense. 

I made a wrong assumption to make this pull request while thinking about my class schedule which is fixed at the term start. But I got your point and you are right, work calendars are dynamic.

**Comment by klimeryk** [comment]
I wish there _was_ a way to marry a PDF generator like this with a more dynamic source like Google Calendar or ICS. But for now, I'm afraid it's one of the other 🙇 I've checked https://github.com/reHackable/awesome-reMarkable, but even there I could not see anything for Google Calendar :(

FWIW, you could try generating a calendar just for the duration of the term (ReCalendar already lets you pick the starting month and how many months you want to generate the calendar for). So you could optimize it for use during that one term. It'd still not pull in from Google Calendar, though 😅
