### ISSUE TITLE
New page on daily itinerary does not work as expected

### ISSUE THREAD

**Issue by peculiarjulia** [klimeryk/recalendar.js#110]
When add a new page to daily itinerary any item you add to the new page also appears at the bottom of the old page. 
In the example below: 'Shopping list' should only appear on the new page.
<img width="1019" alt="Screenshot 2023-11-23 at 11 35 27" src="https://github.com/klimeryk/recalendar.js/assets/7933056/308011c5-1a47-4083-bf54-45a80a322f4a">

**Comment by klimeryk** [comment]
Thanks for reporting! You're absolutely right - not sure how I missed that :) Probably a regression crept in at some point. I've fixed it in https://github.com/klimeryk/recalendar.js/commit/9629ec62594375a965ad42aa1204f6fbe041237a - including on the month overview and week retrospective pages, which had the same issue 🙇
