### ISSUE TITLE
Handle recurring events in iCal import

### ISSUE THREAD

**Issue by abusch** [klimeryk/recalendar.js#111]
I have an iCal calendar for birthdays using events that recur every year that I would like to import in the planner, but it seems the iCal import code, when processing the events, checks the date of the _initial_ event (that I created years ago), and since it doesn't match the current year, it just discards it... It would be nice to handle those and check if there is a recurrence in the current year.

**Comment by Michal-Januszewski** [comment]
I use a local workaround in terminal:
#> more calendar.ics | grep -v DESCRIPTION | grep -v birthday | grep -v RRULE | sed 's/VALUE=DATE:20[0-9][0-9]/VALUE=DATE:2024/g' > fixed_calendar.ics

... but it's ugly ;)
Igor, it would be perfect to do similar processing in .js, but I'm to weak to do the fix right :)

**Comment by klimeryk** [comment]
Thanks for the PR, @abusch! 🙇
