### ISSUE TITLE
the links in the PDF are only active until February 6th

### ISSUE THREAD

**Issue by reneskoda** [klimeryk/recalendar.js#12]
Hi there,

thank you for this great project.

Unfortunately, the links in the PDF are only active until February 6th.

Did I make a mistake or is it a bug in the program?

Kind regards

**Comment by klimeryk** [comment]
Hi, @reneskoda! I'd guess you downloaded the preview PDF - the one generated when clicking the "Refresh preview" button (bottom left blue button):
<img width="1417" alt="Screenshot 2022-01-06 at 09 05 06" src="https://user-images.githubusercontent.com/3392497/148357652-8667ac72-cf92-4dc9-ba62-626bbaf2eea7.png">

However, as mentioned in the header of the right portion, it's just a preview and contains only the first month (to speed up generating the preview). To generate the full PDF, click the gray-ish button under it labeled "Generate full calendar and download". It will take much longer (around 12 times as long as the preview PDF), so be patient :)

Hope this helps - let me know if it resolved your problem 🙌

**Comment by reneskoda** [comment]
@klimeryk 

Thank you very much for your answer. Your answer resolved my problem. I am so happy with your recalendar! :-)

**Comment by klimeryk** [comment]
Great, glad to hear that!
