### ISSUE TITLE
Converting Handwritten notes on Recalendar (Device: Kindle Scribe) into digital text

### ISSUE THREAD

**Issue by Hitcho84** [klimeryk/recalendar.js#120]
hi there
is there a way to convert Handwritten notes on Recalendar (Device: Kindle Scribe) into digital text?

**Comment by klimeryk** [comment]
ReCalendar generates a normal/regular PDF (just the contents is customized to your needs), so any handwritting conversion, etc. is dependent only on what ReMarkable tablets support. Looking [at the official docs](https://support.remarkable.com/s/article/Convert-handwritten-notes-into-text), looks like this is only supported on:

> You can convert handwritten notes in your notebooks, and in note pages you’ve [added](https://support.remarkable.com/s/article/Add-and-delete-files-or-pages) to your PDFs or ebooks.

So, if you add an empty page (using ReMarkable) to your ReCalendar, then it seems it could convert the notes on those extra pages to text. But only on those pages. Not sure why this limitation - that's something that [ReMarkable support](https://support.remarkable.com/s/contactsupport) can help further with 🙇‍♂️ 
Thanks for trying ReCalendar!
