### ISSUE TITLE
Lefthanded adjustments

### ISSUE THREAD

**Issue by bockelaar** [klimeryk/recalendar.js#16]
my remarkable2 is in lefthanded modus. This makes the calendar overlap with the menu, which is, for a lefty, on the right side of the page.
Is there a way to "mirror" the layout of the calendar?

**Comment by klimeryk** [comment]
Left-handed version added to https://recalendar.me/ 🎉  Please let me know if you there are any tweaks you'd like to see.

<img width="1419" alt="Screenshot 2022-01-09 at 20 05 51" src="https://user-images.githubusercontent.com/3392497/148698786-45a1f4be-1903-4bd9-8d1a-4bc1de6fcff5.png">
