### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by steima** [klimeryk/recalendar.js#2]
@klimeryk if I just translate the `.json` files  in `locales` is it a problem if then there are some keys missing from the German translation?

**Comment by klimeryk** [comment]
To be clear, this project is still very much WIP. The JSON files are not ready to be translated - there are missing keys, not all strings are there, etc. I just wanted to put the foundation there to make sure it's set up and integrated with the app. But I'm still shaping the UI, so I did not want to invest too much time in carefully making everything translateable when it could change in the next commit.

**Comment by klimeryk** [comment]
I've finally launched the project 🎉 If you're interested in translating it to German, I've added rudimentary instructions here: https://github.com/klimeryk/recalendar.js/blob/master/TRANSLATIONS.md. Of course, happy to answer any questions or clarify stuff.

**Comment by Marko-S-t** [comment]
Hello.
Is the project with the German translation still active? I would translate the *json files. Could you then add this to your project?

**Comment by frobnia** [comment]
translates json files attached.

[de.zip](https://github.com/klimeryk/recalendar.js/files/10969688/de.zip)

**Comment by Schneppi** [comment]
Seems pretty complete. Will it ever be merged/integrated? 👍

**Comment by Schneppi** [comment]
I've added the files translated by https://github.com/frobnia in a [Pull Request](https://github.com/klimeryk/recalendar.js/pull/69) and hope it will be available on https://recalendar.me/ soon :-)

**Comment by klimeryk** [comment]
Thanks, @frobnia and @Schneppi! I've merged the translations in https://github.com/klimeryk/recalendar.js/commit/684e61045d1d2dd403d868b64ae34dccf7b2c6c6 (after fixing up the file encoding to make sure all the umlauts show up ;)). Hope it work well for you - please feel free to open new issues and/or pull requests if you see anything that needs adjustments 🙇‍♂️
