### ISSUE TITLE
Allow adding permanent padding to accommodate toolbar

### ISSUE THREAD

**Issue by klimeryk** [klimeryk/recalendar.js#21]
Raised on Reddit: https://www.reddit.com/r/RemarkableTablet/comments/rri79w/comment/hs3902b/?utm_source=reddit&utm_medium=web2x&context=3

Should be fairly easy, especially with the global page style now in one place: https://github.com/klimeryk/recalendar.js/blob/master/src/pdf/styles.js#L1. A `paddingLeft` (or right, depending on `isLeftHanded`) does the trick.

<img width="664" alt="Screenshot 2022-01-12 at 22 24 37" src="https://user-images.githubusercontent.com/3392497/149233253-d63d7e8b-41c2-4543-9c7e-81218f537003.png">

**Comment by FlorianKempenich** [comment]
Great feature! 🎉

However, it doesn't work on the month view. Would it be possible to implement it for the month view as well❓
