### ISSUE TITLE
changing language after first preview will not change items

### ISSUE THREAD

**Issue by kimusan** [klimeryk/recalendar.js#22]
Steps:
Use langauge 1 (e.g. english) and then press the "generate preview" button. Then change to language 2 (e.g. Danish) and generate preview again. 

Now the todo item etc in the generated preview will stay in language 1.

This might be because you do not want to touch them if the user has changed the text, but maybe it would be beneficial to check if the values are default and then actually change them.

**Comment by klimeryk** [comment]
> This might be because you do not want to touch them if the user has changed the text, but maybe it would be beneficial to check if the values are default and then actually change them.

That's exactly why 👍 I agree it's not the best experience. And I thought about approaching it like you said. But that has two issues. One is just more complex code. The other is that there is still a chance that the user actually wanted that value and now it silently changed (I agree it's probaby unlikely, but for something like `TODO`, it might be).

Things also complicate after I've added the option to re-order items through drag & drop.

I think the best approach here would be to ensure the user first picks the language and then generates the calendar. So far the language picker is in the "standard" place (top right). But I can also duplicate and/or move it to before selecting the template. BTW, (re-)selecting a template after language change will also "fix" the labels (but that's a bit of a nuclear option).

All that to say, there's no perfect option here, so I'll close for now as wontfix. But I'll definitely keep an eye on this and see if there are more signals that folks are running into this 🙇 Thanks for the report!
