### ISSUE TITLE
Daily Iteneraries don't work for Sunday week Start

### ISSUE THREAD

**Issue by daaknes** [klimeryk/recalendar.js#3]
First, let me say that I love your tools.  The recalendar.me website is incredibly easy to use and I really appreciate your efforts.  While using the calendar generator on recalendar.me I noticed that if you changed the week start to Sunday and then customized the itinerary on Monday and Tuesday that the Monday customization shows up on Sundays and the Tuesday customization would show up on Mondays.  In essence they don't respect the Sunday week start.  I hope I explained that clearly.

Again, absolutely great work and I truly appreciate your time.  I know you said it's free, but but I wouldn't mind donating if you have a link.

Thanks,
Daaknes

**Comment by klimeryk** [comment]
Thanks for the kind words! And trying out the website and reporting the issue - appreciate it!
I understand what you're describing - I thought I had factored that already in, but apparently I did not (or missed this case). I'll have a closer look tonight 🙇

**Comment by klimeryk** [comment]
Yup, I found the issue. As with dates and calendars, it quickly gets complicated, so I was not able to fix it tonight. But hopefully by the end of the year (aka tomorrow ;)).

**Comment by klimeryk** [comment]
Thanks again for the report - should be fixed now!
