### ISSUE TITLE
Special days with "weekend highlighting"

### ISSUE THREAD

**Issue by Hafting** [klimeryk/recalendar.js#31]
Some special days (like constitution day) are not workdays. Printed calendars tend to give such days the same special color/highlighting as the sundays.

It'd be nice if this was an option for the special days we enter into the calendar too.  Birthdays and such may be ordinary workdays when they don't fall in a weekend. But some days are more special than others, i.e. "national holidays".

**Comment by klimeryk** [comment]
Thanks for the suggestion, @Hafting! I haven't thought of that, but it totally makes sense 👍 I've implemented it in https://github.com/klimeryk/recalendar.js/commit/f6529d34735d21e8b3161d3932048f87714b1562 (with an additional fix in https://github.com/klimeryk/recalendar.js/commit/8062d45f85b9f809e33424c99e8ea84e6588bbca...).

<img width="204" alt="Screenshot 2023-04-22 at 16 32 15" src="https://user-images.githubusercontent.com/3392497/233796073-4ca9e14a-b8b3-4ca9-acca-482fd9714530.png">

January 3 and 11 have special holidays now. January 1st actually too, but it's already a weekend.
January 13, Friday, has both an "event" and a "holiday", so both styles are applied.
January 14, Saturday has only an "event", but it's a weekend day, so both styles are applied as well.

Hope that helps!
