### ISSUE TITLE
No crosslinks in minimal calander

### ISSUE THREAD

**Issue by dvdsk** [klimeryk/recalendar.js#32]
Hi,

Thanks for this great app! I like to have a rather minimal calendar however if I chose the minimal preset and generate a calendar there are no crosslinks.

**Comment by dev-ndn** [comment]
What crosslinks are you missing? The links on the week numbers still work, so I can only guess that you mean you would want to have the days also link to the weeks that they belong to? Or maybe even more than that. Probablybest if you could describe your expectation of what should be linked and where it should link towards

**Comment by dvdsk** [comment]
You are right I now see only some crosslinks are broken, apologies for the rather short and non descriptive issue.

#### Issue
When generating the minimal preset the arrows to go to the next month do not work. In the full calendar they bring me to the month overview. I think that as there is no month overview the links do nothing. 

#### Use case
In the calendar I use those arrows to quickly navigate to a  month in the future. Once I arrive at the right month I use the week cross links to get to the right week overview and plan an appointment there. 

#### Solution
It would be great if they would get me the next month in the minimal calendar too. For my use case it does not matter which page (month overview/ 1e week overview/retrospective or any day) since I can use the week cross links to get to the right week overview.

As a workaround I am now using the full calendar. 

I just want to leave by saying I am very happy with it and it is the cornerstone of my organizational system!

**Comment by klimeryk** [comment]
Thanks for reporting, @dvdsk! I've implemented some fixes around this in https://github.com/klimeryk/recalendar.js/commit/5d2e547c2bf2ef150e1292120c10cee9c958767d. However, as explained in https://github.com/klimeryk/recalendar.js/issues/36#issuecomment-1512235206, it's not going to work exactly as you'd expect. On the spot, I cannot think of a way to improve it (without introducing additional complexity) - but open to suggestions!

**Comment by dvdsk** [comment]
I still enjoy using your calendar daily and this will make it a lot faster for me.
