### ISSUE TITLE
Hangs on "Generating preview, please wait - it can take a minute."

### ISSUE THREAD

**Issue by MrHappy** [klimeryk/recalendar.js#34]
Builds fine, starts fine (I don't see any errors).
But hangs on message "Generating preview, please wait - it can take a minute.".
Accessed the site from different machines, different OSes and different browsers...
Where/how can I find out what is wrong?

**Comment by klimeryk** [comment]
How long are you waiting? ;) I've tried optimizing it as much as I could, but there's still a bit of a delay. On the first preview run, the progress bar is using a hardcoded time (average expected from my machine). After that, it uses the time it actually took on your machine, so it should be more accurate. But depending on your machine/OS/browser/load, it might take longer than expected. Though, I'd hope not more than a minute.

If it hangs and never produces anything, I'd love to debug this further. Of course, first place I'd check is the console for any errors, etc. I'm guessing it's not something as obvious? ;)

**Comment by MrHappy** [comment]
I had it waiting some time a go for over an hour ;).
It just has a spinning circle on the right side of the screen and it shows the following 2 messages in the browser developer tools:
```
asm.js type error: var 't' initializer must be literal or const literal-> pdf.worker.aee5e7e6.worker.js:2:1496269
TypeError: D.a.lib is undefined  -> pdf.worker.aee5e7e6.worker.js:2:280791
```

**Comment by klimeryk** [comment]
Hmmm, that's weird. The error message looks like it's coming from a production build, though. Are you getting it on https://recalendar.me or when you start the development server locally (`yarn start`)?
Which version of Node are you using? I recommend using [`nvm`](https://github.com/nvm-sh/nvm/blob/master/README.md) - then you just run `nvm use` in the project's root to get the correct (`16.*`) version of Node.

**Comment by MrHappy** [comment]
I had/havehave Node.JS v18.3.0 installed and, at your recommendation, installed nvm (v8.11.0) and node (v16.16.0).

When I run `yarn start` the dev-tools returns one error:
`TypeError: crypto_js_md5__WEBPACK_IMPORTED_MODULE_8___default.a.lib is undefined  -> bundle.worker.js:28870:20`

When I build it and run `serve -s build` it shows the following errors:
`asm.js type error: var 't' initializer must be literal or const literal  -> pdf.worker.aee5e7e6.worker.js:2:1496269
TypeError: D.a.lib is undefined  -> pdf.worker.aee5e7e6.worker.js:2:280791`

Both 'hang' with spinning circle.
