### ISSUE TITLE
Czech translation

### ISSUE THREAD

**Issue by ondrejkos25** [klimeryk/recalendar.js#38]
Hi, 
in atached files is Czech translation. 
[app.json.txt](https://github.com/klimeryk/recalendar.js/files/9199387/app.json.txt)
[config.json.txt](https://github.com/klimeryk/recalendar.js/files/9199388/config.json.txt)
[pdf.json.txt](https://github.com/klimeryk/recalendar.js/files/9199389/pdf.json.txt)

**Comment by klimeryk** [comment]
Thanks for submitting the translations, @ondrejkos25! 💖 I've added them in https://github.com/klimeryk/recalendar.js/commit/7daeafb653acd9dc0b5bda7694e1dbdb204aa31e. While working on this, I've noticed that the default font, Lato, had troubles rendering some of the letters. Thankfully, it was just a matter of updating it to the newest version. You might have the old version cached in your browser, if you notice missing/misrendered letters, please clear the cache and try again 🙇
