### ISSUE TITLE
Goodnotes support?

### ISSUE THREAD

**Issue by bradleysmith** [klimeryk/recalendar.js#41]
What an amazing idea!

This would be amazing for Goodnotes on the iPad!

I'd be happy to tweak what is necessary myself if you pointed me in the right direction.

Goodnotes template sizes - https://support.goodnotes.com/hc/en-us/articles/4403641962383-What-are-the-page-dimensions-of-built-in-GoodNotes-templates-

**Comment by bradleysmith** [comment]
Scrap that. This works just great for GoodNotes already! Little bit of wasted space right at the bottom but not enough to worry about

**Comment by klimeryk** [comment]
Awesome, glad to know! In the future, I might add an option to select the page size (from presets, like "ReMarkable 1/2", "Supernote A5X", etc. as well as custom, user-defined). Just need to first make sure the layout will scale as needed. Good to know it's already working quite well on Goodnotes!
