### ISSUE TITLE
Save Advanced Configurations so user can easily repeat their personalized configuration

### ISSUE THREAD

**Issue by andpiazza** [klimeryk/recalendar.js#45]
Using the Advanced template, I performed full setup iterating a few times until I got a result I was more or less happy with.

Since I'll be test-driving this fresh new template, thought it could template save configuration time if there would be the possibility of recording my personalized setup.

Not hung up on the implementation, but here's an idea that seems simple and secure: generate an .XML file that is downloaded to user's computer. Later, the user will have the option to import that .XML file with the configurations.

thanks for looking into. This is an amazing resource!

**Comment by klimeryk** [comment]
That's already done! The PDF itself contains the configuration (in an embedded JSON file). You can then load up the PDF file into the configurator and the configurations will all be reloaded.

<img width="708" alt="Screenshot 2023-04-13 at 23 21 09" src="https://user-images.githubusercontent.com/3392497/231903382-2d7eae78-88d1-44e5-a1af-3b2463e9329d.png">

It's mentioned on the https://recalendar.me/features page:
<img width="319" alt="Screenshot 2023-04-13 at 23 19 58" src="https://user-images.githubusercontent.com/3392497/231903349-cb424222-4f42-4042-a860-c8bce3f08532.png">
