### ISSUE TITLE
Turkish language support

### ISSUE THREAD

**Issue by strasbourgeois** [klimeryk/recalendar.js#46]
Could you please add Turkish language support? I can take care of the translation if needed.

**Comment by klimeryk** [comment]
Absolutely - please follow the instructions at https://github.com/klimeryk/recalendar.js/blob/master/TRANSLATIONS.md and attach the files here 🙏

**Comment by kubiku0** [comment]
[recalendar.zip](https://github.com/klimeryk/recalendar.js/files/11562615/recalendar.zip)
