### ISSUE TITLE
Dutch language support

### ISSUE THREAD

**Issue by OpenAI-coder** [klimeryk/recalendar.js#50]
Hi,
I would appreciate the support of the Dutch language. For the Dutch "Nederlands" language, you can use this:

This is the Dutch name of the months:
Januari - Jan
Februari - Feb
Maart - Maa
April - Apr
Mei - Mei
Juni - Jun
Juli - Jul
Augustus - Aug
September - Sep
Oktober - Okt
November - Nov
December - Dec

This is the Dutch name of the days:
Maandag - Ma
Dinsdag - Di
Woensdag - Wo
Donderdag - Do
Vrijdag - Vr
Zaterdag - Za
Zondag - Zo

This is the English to Dutch translation:
Week = Week
Habits = Gewoontes
Retrospective for weeks = Terugblik op week

Anything I'm missing?

**Comment by klimeryk** [comment]
That part is actually handled automatically. What I need help with is translating the interface and a few strings inside the PDF itself. See https://github.com/klimeryk/recalendar.js/blob/master/TRANSLATIONS.md instructions on how you can help translating ReCalendar into your language 🙏

**Comment by klimeryk** [comment]
Fixed by #91! ❤️ Thanks, @HenkKalkwater! 🙇‍♂️
