### ISSUE TITLE
Link for week 1 of 2022 goes to page for week 1 of 2023

### ISSUE THREAD

**Issue by Parmandil** [klimeryk/recalendar.js#57]
When I click on the link for week 1 of 2022, instead it takes me to the page for week 1 of 2023. This is true wherever the link occurs: 1) the year page, 2) the monthly page for January 2022, 3) weekly and daily pages throughout January 2022.

I created a 12-month calendar beginning with January 2022. I think that should be all that is needed to reproduce the bug, but if my other settings are more relevant than I think, let me know. :)

**Comment by klimeryk** [comment]
Thanks for the report! However, I cannot seem to reproduce it, see this file: 
[recalendar-1.pdf](https://github.com/klimeryk/recalendar.js/files/11227121/recalendar-1.pdf)
(generated it by using the default settings and changing the year to 2022)

I've checked and there was an bug in the code that would cause this behaviour (links were only based on the number of the week), but I've fixed it in https://github.com/klimeryk/recalendar.js/commit/7d1641f148334ba58ff58ba8191c48d71605e5c0 (week links are now based on the number of the week _and_ the year). Maybe you've generated this calendar before that fix was deployed? Closing for now, but please re-open if you can still reproduce 🙇
