### ISSUE TITLE
Italian translation

### ISSUE THREAD

**Issue by Anidro** [klimeryk/recalendar.js#58]
I have completed the Italian translation of the project.
Please see the file attached.
[it.zip](https://github.com/klimeryk/recalendar.js/files/10383441/it.zip)

**Comment by klimeryk** [comment]
Thank you for taking the time to translate ReCalendar to your language, @Anidro! Sorry it took me a while to get to this, but I've added Italian support and your translations in https://github.com/klimeryk/recalendar.js/commit/0256df0f1736c45e948255fd8a3dc82bea487423 🙇‍♂️
