### ISSUE TITLE
Weekend bolding

### ISSUE THREAD

**Issue by Anzus** [klimeryk/recalendar.js#6]
The last two days of the week are always bolded, I assume for the weekend? When selecting Sunday as the start of the week, it would be nice to be able to bold the first and last days of the week.

**Comment by klimeryk** [comment]
Thanks for the report, @Anzus! You're absolutely right - it's a bug. I've fixed it in https://github.com/klimeryk/recalendar.js/commit/444066fc40c44f1a13b4ba98685a0e1cb93266e1 and now the calendar should properly take into account what is the first day of the week and how the weekends relate to that 🙇

**Comment by devenv** [comment]
Actually where I'm from - Friday-Saturday are considered weekend, I think it needs to be configurable :)

**Comment by klimeryk** [comment]
Yeah, that's next on my list. While looking into this issue I was like "right, I know my friends from Israel have a different weekend than me... but what about other cultures... _checks Wikipedia_ ...yup, it's complicated" 😅 I've created https://github.com/klimeryk/recalendar.js/issues/10 to track it 🙇
