### ISSUE TITLE
Issue Feedback

### ISSUE THREAD

**Issue by Gaibhne** [klimeryk/recalendar.js#62]
It seems like this project is in active development, yet the issue tracker goes unanswered. Certainly, in an open source project no support of any kind is owed, and I don't mean for this to come over as a complaint. I'm just wondering; should issues be reported elsewhere, maybe a forum or a third party issue tracker ? Or does this project need support in the form of volunteers to categorize and curate issues for the actual developers ?

Just to be clear, this thing is a fantastic project, and already at it's current state it's probably the greatest thing I've found at least this month, if not this year!

**Comment by klimeryk** [comment]
Hi, @Gaibhne! Thanks for sharing your honest feedback, I truly appreciate it 🙇

To clarify, the project has _not_ been in active development in the last few months:
<img width="455" alt="Screenshot 2023-04-09 at 18 02 11" src="https://user-images.githubusercontent.com/3392497/230788974-6ec37ad9-0f00-491f-b4ee-f49bd6e4bdf2.png">

Only recently I've started going through the backlog. Like you mentioned, the project was good enough and, as usual, other priorities got in the way as well. But I'll try to triage the existing issues (appreciate the community that has grown around the project, it seems!) and continue development.

And, as with any open-source project, if the author goes AWOL, someone dedicated to the project could pick it up and create an active fork. This project is actually extremely easy to host - it's just frontend (HTML, CSS, JS), so the most basic hosting will do (for example, GitHub Pages). But hopefully if it ever comes to that, I'd find someone to proactively take ownership of the project versus me just disappearing 🙇 

Hope this clarifies things and thanks for using ReCalendar!
