### ISSUE TITLE
recalendar not working?

### ISSUE THREAD

**Issue by LogicCoding** [klimeryk/recalendar.js#64]
Hi, earlier today I was able to perfectly generate and download a calendar, however, I have tried to generate another calendar and it simply is not working.
For example, when I add a special date, after clicking on **Add Date**, the page just goes blank.
Another example, I try to create a new calendar, and even when I try to preview the basic template, some things come out "smushed" and on top of each other. Like on Day Itineraries, the Day and Date Number are displayed on top of each other, and the mini calendar in the top right is crossing over to the itinerary lines and looks squished.
I'm not sure if it is just me experiencing these issues, but I tried to use the site on two different browsers, Chrome and Opera, and got the same results.

**Comment by LogicCoding** [comment]
Update: I tried to use recalendar on two other devices and the same issues were happening. For some reason generating a calendar with day itineraries and adding special dates results in errors.

**Comment by klimeryk** [comment]
Same issue as https://github.com/klimeryk/recalendar.js/issues/65. Should be resolved 🙇‍♂️
