### ISSUE TITLE
Most recent update seems to have broken flow for adding page breaks

### ISSUE THREAD

**Issue by Strixin** [klimeryk/recalendar.js#65]
Generated a functional calendar last week with no irregularities when adding page breaks to the daily tasks.
Today when trying to achieve the same thing it appears page breaks with additional fields/lines added after the page break cause the monthly calendar shortcut at the top of the day page to condense and break formatting.

Screenshot attached is of the base "advanced" selection with no additional changes. This is tested across both Safari and Chrome with cookies/page history/data cleared.

<img width="698" alt="Screenshot 2023-04-07 at 1 50 39 pm" src="https://user-images.githubusercontent.com/12171450/230549686-22b4e108-cbe9-4276-a1e1-b4832f125f2e.png">

**Comment by klimeryk** [comment]
Thanks for reporting this! Looks like the newest update broke something 🤔 For the time being, I've reverted to the previous version (this version "only" added the ability to re-order habits, itineraries, etc. through drag & drop).
I've tested and now it's working as expected 🙇‍♂️

**Comment by Strixin** [comment]
Only added! Hah! They were awesome features and I was very much looking forward to using them. Thanks for rolling back. Of note, loading older saved planners also broke at the same time. You couldn’t edit them, only add new fields. Thanks for your hard work.

**Comment by klimeryk** [comment]
Sorry for the trouble, @Strixin 🙇 I've made some fixes and uploaded a new version - it should be working correctly _and_ support drag&drop to re-order the items! Give it a whirl and let me know if you notice any issues 🤞
