### ISSUE TITLE
Feature Request: Week overviews only

### ISSUE THREAD

**Issue by alan412** [klimeryk/recalendar.js#7]
Love the way this looks!

Would it be possible to have an option where it generated the year at a glance and then ONLY the week overview for each week.
(ie, no month overview, no daily item, no retrospective)

Any day in a week would be a link to the week overview.

**Comment by AntonioBlaGra** [comment]
In my case, the reason I am considering using calendar with no itinerary days is that in the remarkable cellphone app links don't work, making it hard to jump to other month, (lot of scrolling). Consulting my calendar in the phone is very handy. reMarkable template actually do not have day itineraries.

**Comment by alan412** [comment]
Sounds good.   I am happy to help if you would like.

**Comment by klimeryk** [comment]
FWIW, I'll work on this tomorrow or the day after. Letting you know to avoid duplicating efforts :)

**Comment by alan412** [comment]
Thanks for letting me know!

**Comment by klimeryk** [comment]
As of https://github.com/klimeryk/recalendar.js/commit/195ae7a6175196bbccc4dda21abbb3b7663b3126 this should be implemented. You can now disable basically all pages (except the year overview... and now I probably jinxed myself and someone will ask for it 🤣 ). You can actually disable individual day pages (if you never intend to write on Saturday and Sunday, for example). The navigation links should take that into account and "skip over" those disabled days.

Hope this helps!

**Comment by alan412** [comment]
Looks good.  Although it seems like if a day is disabled, the navigation should follow these rules:
 - If a week overview, go there.
 - Elif a month overview, go there.
 - Elif a year overview, go there.
 - Else, no navigation

**Comment by alan412** [comment]
Also, the month navigation should work the same way.

**Comment by klimeryk** [comment]
That's already how it's working, as far as I understand. Could you explain what behaviour you expect in more detail? What do you mean by "navigation" in this context?

**Comment by alan412** [comment]
When I click on a day in the month calendar in the corner or on the year
calendar at the front,  it behaves like a link but doesn't take me
anywhere.   If I click on the Week # it does.

--Alan
