### ISSUE TITLE
reMarkable Keyboard

### ISSUE THREAD

**Issue by LHLite** [klimeryk/recalendar.js#71]
Inability to type into recalendar utilizing the newly released remarkable keyboard.

**Comment by klimeryk** [comment]
I don't have the keyboard, so it's hard for me to replicate/verify this. Could you clarify what's not working exactly? ReCalendar ultimately generates a normal PDF file, it should work as any other file with the keyboard.

**Comment by LHLite** [comment]
Hi and thanks for your reply.The keyboard does not write (type) text to the recalender for some reason.Thanks,Les Hanson3375156413On May 20, 2023, at 12:51 PM, Igor Klimer ***@***.***> wrote:﻿
I don't have the keyboard, so it's hard for me to replicate/verify this. Could you clarify what's not working exactly? ReCalendar ultimately generates a normal PDF file, it should work as any other file with the keyboard.

**Comment by klimeryk** [comment]
Thanks for confirming that, @ovidiusoft. I had a suspicion that it was a limitation of the tablet's software itself. I'd imagine sooner or later they'll add an ability to create ad-hoc "text boxes" where you can type in any PDF or something similar. Until then there's indeed nothing I can do about it 🙇

**Comment by LHLite** [comment]
I very much appreciate the response from you. I will reach out to ReMarkable for a bug fix opportunity. 

 

Thanks,

 

Les-
