### ISSUE TITLE
Attempt for Turkish translation

### ISSUE THREAD

**Issue by kubiku0** [klimeryk/recalendar.js#77]
[recalendar.zip](https://github.com/klimeryk/recalendar.js/files/11548799/recalendar.zip)

**Comment by klimeryk** [comment]
@kubiku0, thanks for submitting the Turkish translations! There seems to be an issue with the `app.json` file, though. Looks like it ends after line 49 - but there should be ~164 lines (see [the English app.json](https://github.com/klimeryk/recalendar.js/blob/master/src/locales/en/app.json)). Could you please check if maybe the file did not save or something? 🙏

**Comment by kubiku0** [comment]
I like your project and I tried to translate it into Turkish so that other Turkish users can use it in their own language. I apologize for any mistakes I made.
[recalendar.zip](https://github.com/klimeryk/recalendar.js/files/11576173/recalendar.zip)

**Comment by kubiku0** [comment]
I like your project and I tried to translate it into Turkish so that other Turkish users can use it in their own language. I apologize for any mistakes I made.
[recalendar.zip](https://github.com/klimeryk/recalendar.js/files/11576252/recalendar.zip)

**Comment by klimeryk** [comment]
No worries, @kubiku0, I deeply appreciate your help! The translations look great - I've included them in the app in https://github.com/klimeryk/recalendar.js/commit/ae54fbfd2bb9657b6343f7df8c3facc271504698. You can try them out for yourself now - let me know if you spot anything you'd like to improve in them!

<img width="1437" alt="Screenshot 2023-05-26 at 20 29 32" src="https://github.com/klimeryk/recalendar.js/assets/3392497/9e839089-cd52-40f8-abce-c0e6f5b0e235">

**Comment by kubiku0** [comment]
I think there was a problem with the file I sent.
The letters "ı " "ş" "ğ" do not appear correctly. I saved and reposted in UTF-8 Format.
[recalendar.zip](https://github.com/klimeryk/recalendar.js/files/11581577/recalendar.zip)

**Comment by klimeryk** [comment]
Thanks for the follow-up, @kubiku0! Indeed, the original files were not UTF-8 so I had to convert them. I thought I did it properly, but obviously something went wrong. Thanks for the UTF-8 ones - I've updated the translations in https://github.com/klimeryk/recalendar.js/commit/007c20be8372d414d87956f3716d5d70b7dd67bd with the new files and I hope everything looks better now!

**Comment by kubiku0** [comment]
Thank you for everything. It's been great .  Greetings from Ankara, Türkiye.
