### ISSUE TITLE
Special dates are not rendered in the day boxes in the Weekly view

### ISSUE THREAD

**Issue by ovidiusoft** [klimeryk/recalendar.js#79]
(I am not a React expert, so I might say stupid things) It looks from the code in **/src/pdf/pages/week-overview.jsx** that the special dates should be rendered inside each day box in the weekly page. The generated PDF does not include them (there should be entries on Jan 13th and 14th from the sample data). The events appear correctly in the day pages for 13 and 14.

<img width="303" alt="Screenshot 2023-05-26 at 10 40 59" src="https://github.com/klimeryk/recalendar.js/assets/1104994/aa5a6fbf-ae33-4d76-8c7a-5b0931b02d83">

**Comment by klimeryk** [comment]
You're absolutely right - thanks for reporting this regression! It sneaked in when fixing #31 in https://github.com/klimeryk/recalendar.js/commit/f6529d34735d21e8b3161d3932048f87714b1562. It should be fixed now 🙇
