### ISSUE TITLE
Week numbers are off by 1 if Sunday is the first day of the week

### ISSUE THREAD

**Issue by Anzus** [klimeryk/recalendar.js#8]
If the week starts with Sunday, then the generated calendar has the week numbers off by 1

![Screen Shot 2022-01-02 at 1 08 32 PM](https://user-images.githubusercontent.com/8584460/147888170-dc870a1f-397e-4c4d-a6d3-67d07309bdc5.jpg)

**Comment by klimeryk** [comment]
Huh, I thought I fixed it in https://github.com/klimeryk/recalendar.js/issues/4 🤔 But you're right - the bug is there (still or again).

**Comment by klimeryk** [comment]
Looks like I forgot an important lesson from my previous version of this project: to accurately calculate the week number, one has to look at... Thursday of that week. Cause, in the example above, the second of January actually belongs to week 52. And I was using the first day of the week to calculate the week number. But, as usual, things are not that simple (they never are with dates and programming). See https://en.wikipedia.org/wiki/ISO_week_date for the full explanation, but this part is crucial:

> Weeks start with Monday and end on Sunday. Each week's year is the Gregorian year in which the Thursday falls. The first week of the year, hence, always contains 4 January. ISO week year numbering therefore usually deviates by 1 from the Gregorian for some days close to 1 January. 

Anyway, this should be fixed now! Thanks again for reporting!

**Comment by Anzus** [comment]
Oh, I totally get that dates are hard.
