### ISSUE TITLE
non mi si genera il calendario, anche dopo tre o 4 minuti

### ISSUE THREAD

**Issue by bobfra4** [klimeryk/recalendar.js#80]
che devo fare ?

**Comment by ilbonte** [comment]
Prova a cambiare browser, ti consiglio google chrome ed assicurati di avere una versione aggiornata. 

Se ancora non funziona fai 
(1) tasto destro -> (2) ispeziona elemento e poi vai sul tab console ->  (3) e fai partire la generazione

Controlla se ti esce qualche errore in rosso (4) ed eventualmente riportalo qui uno screenshot

![image](https://github.com/klimeryk/recalendar.js/assets/7412876/9c61ed14-31da-4eb5-bdb3-2e4416778d1c)

**Comment by klimeryk** [comment]
Closing as I'm hoping it was solved. If you still can't make it work, please re-open and add more details:
 - What operating system and browser are you using?
 - Are you changing any settings or even just default ones don't work for you?
 - Any errors, like @ilbonte mentioned above? (thank you!)
 - Have you tried in a different browser/device?
