### ISSUE TITLE
Open this just to say great job! Feel free to close right away

### ISSUE THREAD

**Issue by kychris** [klimeryk/recalendar.js#85]
Very nicely organized code, and very simple yet robust feature sets. 

I am able to get around the code base and change line height very easily myself due to the organized nature. 

The fact that you can upload previously generated pdf for config is such a nice touch, and the fact that it works so well it is simple chef's kiss.

**Comment by klimeryk** [comment]
Thank you for the kind words! ❤️ 
FWIW, I'm hoping to add an option to also easily change the line height from the UI - hopefully by the end of the year. Glad you were able to make the change yourself in the code, though!
