### ISSUE TITLE
emoji i not showing in the generated pdf

### ISSUE THREAD

**Issue by moloean** [klimeryk/recalendar.js#86]
When I add a special date, I use emoji like 🎂 (Birthday Cake) for Birthdays,  🇳🇴 (Norwegian flag) for national flag days and etc.

**Comment by klimeryk** [comment]
Thanks for the report and suggestion! While PDFs don't support emojis, [the library I'm using actually has a nice workaround](https://react-pdf.org/fonts#registeremojisource) (embed emojis as images), so it was an easy fix!

<img width="428" alt="Screenshot 2023-10-07 at 22 43 49" src="https://github.com/klimeryk/recalendar.js/assets/3392497/0651f919-4cd4-4307-bc66-b69d66b117ff">

Note that this is using the [Twemoji font from Twitter](https://github.com/twitter/twemoji). So it might not render exactly as on your device - that's just a quirk of emojis. Kinda like with regular fonts - the word is the same, just rendered different depending on the emoji font on the device. Hope this helps! 🎉 🚀 🙇‍♂️
