### ISSUE TITLE
Selecting template under start do not seam to work 

### ISSUE THREAD

**Issue by moloean** [klimeryk/recalendar.js#89]
when I click one of the templates "buttons", I ant see that it doesn't do anything.

**Comment by ilbonte** [comment]
with black and minimalistic it crashes because an object is passed instead of an array 
the exception is
```   at config.js:159:30
    at Array.forEach (<anonymous>)
    at e.value (config.js:157:28)
    at new e (config.js:145:8)
    at e.handleTemplateSelect (configuration-selector.jsx:127:18)
    ```


![image](https://github.com/klimeryk/recalendar.js/assets/7412876/9d4ddc2c-4ef0-43ff-b7d5-826149d074af)

**Comment by klimeryk** [comment]
Yup, same issue as https://github.com/klimeryk/recalendar.js/issues/97. Just pushed a fix for it: https://github.com/klimeryk/recalendar.js/commit/5a063264c6214f72fcaa4e8a71ceefa336a28440.
Thanks for the report and sorry for the issue!
