### ISSUE TITLE
Feature Request:  Allow creating default day itinerary

### ISSUE THREAD

**Issue by alan412** [klimeryk/recalendar.js#9]
Have a default day itinerary and then you can override any day of the week with a different one but the others ones all go to the default.

**Comment by klimeryk** [comment]
Hi again, @alan412! :) Yup, that would be indeed a handy feature. I can imagine with more complicated day itineraries, it could be a PITA to fill out each day. So in https://github.com/klimeryk/recalendar.js/commit/1dd7853d429424ad0c15a41d461648a76a681271 I added a button to copy the given day to all other days:

<img width="662" alt="Screenshot 2022-01-03 at 20 30 10" src="https://user-images.githubusercontent.com/3392497/147977188-e3465235-6e30-4c2f-928c-bda27004eba5.png">

So, you fill out the itinerary for your first day, copy it to all others. And then optionally tweak it per day. But probably easier than doing it day by day. Thanks for the suggestion!

**Comment by alan412** [comment]
Looks great, thanks!!
