### ISSUE TITLE
Language: Greek

### ISSUE THREAD

**Issue by WildroseGT** [klimeryk/recalendar.js#96]
Hello, I would appreciate it if you could include the Greek language. In any case, even if you can't, you've done an incredible job. Thank you!

**Comment by klimeryk** [comment]
Hi, @WildroseGT! I'd love to offer ReCalendar in all possible languages, but it's a community effort. There are [instructions here](https://github.com/klimeryk/recalendar.js/blob/master/TRANSLATIONS.md) if you'd like to help out!
However, this made me thinking of a possible compromise. I could actually already offer at least the days of the week and month names translated in various languages (the translations are provided by a third-party library I'm using, [dayjs](https://day.js.org/)). So I've done that in https://github.com/klimeryk/recalendar.js/commit/cff4b2e1ba061cf07a9f012208f437afced88087.

You can now select Greek (and maaaany other languages). However, as mentioned above, please note that the configurator itself will remain in English and only the days of the week and month names will get translated. But I'd say it's 80% done by default and you can tweak a bit more to get it closer to fully translated:

<img width="624" alt="Screenshot 2023-10-15 at 21 00 27" src="https://github.com/klimeryk/recalendar.js/assets/3392497/34bd7851-df91-4fcf-a51f-c54eb1301692">
<img width="624" alt="Screenshot 2023-10-15 at 21 00 33" src="https://github.com/klimeryk/recalendar.js/assets/3392497/05aa49d3-981a-4c46-a550-1a27f09a3003">

I'm gonna close this issue as fixed-ish. But if you want to provide the full translations (or someone else!), please either re-open or create a new issue 🙇‍♂️

**Comment by WildroseGT** [comment]
Hi

Thank you so much for your quick response and for the effort you've put
into making ReCalendar more accessible in different languages. I appreciate
the option to select Greek and other languages. This is a fantastic
addition that will benefit many users. Your work is greatly appreciated.

I'll definitely check out the instructions for helping with translations,
and I look forward to contributing in any way I can to make ReCalendar even
more inclusive.

Thanks again for your dedication to this project.

Best regards, WildroseGT
__________________________________
*George Tsirigotis*
Senior Network Engineer
Email:    ***@***.***
Mobile:  +30-6977-214642
LinkedIn  : https://www.linkedin.com/in/george-tsirigotis-6a740127
Web Site : https://sites.google.com/site/otexnikossas/
                 https://wildrosemail.wixsite.com/george-tsirigotis
Skype     : Wildrose_phone
