### ISSUE TITLE
Bug Report: Template Buttons Nonfunctional

### ISSUE THREAD

**Issue by Gaibhne** [klimeryk/recalendar.js#97]
Title really says it all, reproduced in FF and Chrome, current versions, plugins disabled.

Console shows errors such as:

```
Uncaught TypeError: n.map is not a function
    value config.js:159
    value config.js:157
    e config.js:145
    handleTemplateSelect configuration-selector.jsx:127
    React 16
    <anonymous> index.js:47
    <anonymous> index.js:51
    <anonymous> index.js:51
```

**Comment by klimeryk** [comment]
Thanks for the report! I introduced that bug when revamping special dates in https://github.com/klimeryk/recalendar.js/commit/f6529d34735d21e8b3161d3932048f87714b1562. It should be fixed now 🙇
