### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by Stefan71a** [klimeryk/recalendar.js#98]
Here is a Swedish package to be used. 
In the English file app.jason file add "sv": "Svenska" - I´ve added it into the Swedish translated file.

[sv.zip](https://github.com/klimeryk/recalendar.js/files/12700669/sv.zip)

**Comment by klimeryk** [comment]
Thanks @Stefan71a for the translation files! I've merged them in https://github.com/klimeryk/recalendar.js/commit/feff2ab95687d02cb5acf25197eaf011691a1f1a and now you can use them 👍
